name: Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      # Deteksi otomatis output folder (Vite biasa = dist, CRA = build)
      - name: Resolve output dir
        id: outdir
        run: |
          if [ -d "dist" ]; then echo "dir=dist" >> $GITHUB_OUTPUT;
          elif [ -d "build" ]; then echo "dir=build" >> $GITHUB_OUTPUT;
          else echo "dir=dist" >> $GITHUB_OUTPUT; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.outdir.outputs.dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      # URL akan diisi otomatis oleh step deploy
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
